name: My Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 21f1005206@ds.study.iitm.ac.in
        run: echo "Hello, world! My email is 21f1005206@ds.study.iitm.ac.in"
